// Initial Card Configuration for Employment Agreement

import { SmartCard, CardCluster } from './types';

export const initialCards: SmartCard[] = [
  // BASICS
  {
    id: 'employee-name',
    type: 'person',
    category: 'basics',
    icon: 'User',
    label: 'Employee Name',
    placeholder: 'e.g., Sarah Chen',
    value: null,
    state: 'empty',
    order: 1,
    required: true,
    relatedCards: ['role', 'level'],
    validationRules: [
      {
        type: 'required',
        message: 'Employee name is required',
        validate: (value) => !!value && value.length > 0,
      },
    ],
  },
  {
    id: 'role',
    type: 'role',
    category: 'basics',
    icon: 'Briefcase',
    label: 'Job Title',
    placeholder: 'e.g., Software Engineer',
    value: null,
    state: 'empty',
    order: 2,
    required: true,
    relatedCards: ['level', 'department'],
  },
  {
    id: 'level',
    type: 'role',
    category: 'basics',
    icon: 'TrendingUp',
    label: 'Level',
    placeholder: 'e.g., Senior, Lead, Principal',
    value: null,
    state: 'empty',
    order: 3,
    required: false,
  },
  {
    id: 'department',
    type: 'role',
    category: 'basics',
    icon: 'Building2',
    label: 'Department',
    placeholder: 'e.g., Engineering, Sales',
    value: null,
    state: 'empty',
    order: 4,
    required: false,
  },
  {
    id: 'start-date',
    type: 'date',
    category: 'basics',
    icon: 'Calendar',
    label: 'Start Date',
    placeholder: 'e.g., June 1, 2025',
    value: null,
    state: 'empty',
    order: 5,
    required: true,
  },
  {
    id: 'location',
    type: 'location',
    category: 'basics',
    icon: 'MapPin',
    label: 'Work Location',
    placeholder: 'e.g., San Francisco, CA',
    value: null,
    state: 'empty',
    order: 6,
    required: true,
    relatedCards: ['remote-policy'],
  },
  {
    id: 'remote-policy',
    type: 'custom',
    category: 'basics',
    icon: 'Laptop',
    label: 'Remote Work',
    placeholder: 'e.g., Hybrid, Full Remote',
    value: null,
    state: 'empty',
    order: 7,
    required: false,
  },

  // COMPENSATION
  {
    id: 'salary',
    type: 'compensation',
    category: 'compensation',
    icon: 'DollarSign',
    label: 'Base Salary',
    placeholder: 'e.g., $180,000',
    value: null,
    state: 'empty',
    order: 1,
    required: true,
    relatedCards: ['bonus', 'equity'],
  },
  {
    id: 'pay-frequency',
    type: 'compensation',
    category: 'compensation',
    icon: 'Calendar',
    label: 'Pay Schedule',
    placeholder: 'e.g., Bi-weekly, Monthly',
    value: null,
    state: 'empty',
    order: 2,
    required: true,
  },
  {
    id: 'bonus',
    type: 'compensation',
    category: 'compensation',
    icon: 'Gift',
    label: 'Bonus',
    placeholder: 'e.g., 10% annual bonus',
    value: null,
    state: 'empty',
    order: 3,
    required: false,
  },
  {
    id: 'equity',
    type: 'compensation',
    category: 'compensation',
    icon: 'TrendingUp',
    label: 'Equity/Stock',
    placeholder: 'e.g., 0.25% equity',
    value: null,
    state: 'empty',
    order: 4,
    required: false,
    relatedCards: ['vesting', 'cliff'],
  },
  {
    id: 'vesting',
    type: 'compensation',
    category: 'compensation',
    icon: 'Clock',
    label: 'Vesting Period',
    placeholder: 'e.g., 4 years',
    value: null,
    state: 'empty',
    order: 5,
    required: false,
  },
  {
    id: 'cliff',
    type: 'compensation',
    category: 'compensation',
    icon: 'Shield',
    label: 'Cliff Period',
    placeholder: 'e.g., 1 year',
    value: null,
    state: 'empty',
    order: 6,
    required: false,
  },

  // BENEFITS
  {
    id: 'health-insurance',
    type: 'benefit',
    category: 'benefits',
    icon: 'Heart',
    label: 'Health Insurance',
    placeholder: 'e.g., Full coverage',
    value: null,
    state: 'empty',
    order: 1,
    required: false,
  },
  {
    id: 'pto',
    type: 'benefit',
    category: 'benefits',
    icon: 'Palmtree',
    label: 'Paid Time Off',
    placeholder: 'e.g., 20 days/year',
    value: null,
    state: 'empty',
    order: 2,
    required: false,
  },
  {
    id: 'retirement',
    type: 'benefit',
    category: 'benefits',
    icon: 'PiggyBank',
    label: '401k/Retirement',
    placeholder: 'e.g., 4% match',
    value: null,
    state: 'empty',
    order: 3,
    required: false,
  },

  // LEGAL PROTECTION
  {
    id: 'nda',
    type: 'legal',
    category: 'legal',
    icon: 'Lock',
    label: 'NDA/Confidentiality',
    placeholder: 'Standard NDA',
    value: null,
    state: 'empty',
    order: 1,
    required: true,
  },
  {
    id: 'ip-rights',
    type: 'legal',
    category: 'legal',
    icon: 'Lightbulb',
    label: 'IP Rights',
    placeholder: 'Work-for-hire',
    value: null,
    state: 'empty',
    order: 2,
    required: true,
  },
  {
    id: 'non-compete',
    type: 'legal',
    category: 'legal',
    icon: 'Ban',
    label: 'Non-Compete',
    placeholder: 'Optional',
    value: null,
    state: 'empty',
    order: 3,
    required: false,
  },
  {
    id: 'non-solicitation',
    type: 'legal',
    category: 'legal',
    icon: 'UserX',
    label: 'Non-Solicitation',
    placeholder: '1 year restriction',
    value: null,
    state: 'empty',
    order: 4,
    required: false,
  },

  // TERMINATION
  {
    id: 'employment-type',
    type: 'custom',
    category: 'termination',
    icon: 'FileText',
    label: 'Employment Type',
    placeholder: 'e.g., At-will',
    value: null,
    state: 'empty',
    order: 1,
    required: true,
  },
  {
    id: 'notice-period',
    type: 'custom',
    category: 'termination',
    icon: 'Bell',
    label: 'Notice Period',
    placeholder: 'e.g., 2 weeks',
    value: null,
    state: 'empty',
    order: 2,
    required: true,
  },
  {
    id: 'severance',
    type: 'custom',
    category: 'termination',
    icon: 'HandCoins',
    label: 'Severance',
    placeholder: 'Optional',
    value: null,
    state: 'empty',
    order: 3,
    required: false,
  },
];

export const initialClusters: Omit<CardCluster, 'cards' | 'completionPercentage'>[] = [
  {
    id: 'basics',
    title: 'Basics',
    category: 'basics',
    required: true,
    icon: 'User',
  },
  {
    id: 'compensation',
    title: 'Compensation',
    category: 'compensation',
    required: true,
    icon: 'DollarSign',
  },
  {
    id: 'benefits',
    title: 'Benefits',
    category: 'benefits',
    required: false,
    icon: 'Heart',
  },
  {
    id: 'legal',
    title: 'Legal Protection',
    category: 'legal',
    required: true,
    icon: 'Shield',
  },
  {
    id: 'termination',
    title: 'Termination',
    category: 'termination',
    required: true,
    icon: 'FileX',
  },
];
